# Generated by Django 5.1 on 2024-08-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_reviewer_content_en_reviewer_content_fil'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='key_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='key_fil',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
    ]
