# Generated by Django 5.1 on 2024-12-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_question_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
