# Generated by Django 4.1.5 on 2024-07-09 20:10

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_download_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=50)),
                ('content', mdeditor.fields.MDTextField(blank=True, null=True)),
            ],
        ),
    ]
