# Generated by Django 4.1.5 on 2024-07-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Traffic Rules and Regulations(Car)'), (1, 'Road Signage(Car)'), (2, 'Vehicle Basic Parts(Car)'), (3, 'Traffic Rules and Regulations(Motorcycle)'), (4, 'Road Signage(Motorcycle)'), (5, 'Vehicle Basic Parts(Motorcycle)')], default=0),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='key',
            field=models.CharField(max_length=50),
        ),
    ]
