# Generated by Django 4.1.5 on 2024-07-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_reviewer_category_reviewer_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='key',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
