# Generated by Django 4.1.5 on 2024-07-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_reviewer_updated_at_alter_reviewer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='order_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='reviewer',
            unique_together={('category', 'order_position')},
        ),
    ]
